In [1]:
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error,mean_absolute_percentage_error
from sklearn.model_selection import KFold

data=pd.read_excel(r'D:\AI4polymer\cocrystal design\Data-0320\deltaML result\deltaML4DFT_rawMD_merged_data_0512.xlsx')
data_PTT = data.dropna(subset=['photothermal'])
data_PTT.reset_index(drop=True, inplace=True)
data_PDT = data.dropna(subset=['photodynamic'])
data_PDT.reset_index(drop=True, inplace=True)

In [2]:
data_PTT=data_PTT.dropna()
data_PTT.reset_index(drop=True, inplace=True)
data_PDT=data_PDT.dropna()
data_PDT.reset_index(drop=True, inplace=True)

## 1. PTT

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)
data_PTT["PTT_bin"] = data_PTT["photothermal"].astype(str).replace({"middle": "weak"})
data_PTT['PTT_bin'].value_counts()

PTT_bin
strong    129
weak      114
Name: count, dtype: int64

In [ ]:
DFT_cols =[
    'es1_ev_high_pred',
    'fs1_high_pred',
    'et1_ev_high_pred',
    'delta_est_ev_high_pred',
    'min_abs_s1_tn_ev_high_pred',
    'd_index_ang_high_pred',
    't_index_ang_high_pred',
    'zpe_ha_pred',
    'gcorr_ha_pred',
    'alpha_iso_bohr3_pred',
    's_vib_cal_molk_pred',
    'svib_frac_pred',
    'hlg_kjmol_high_pred',
    'dipole_gs_debye_high_pred',
    'ci_index',]

MD_cols=['vdw_energy_kjmol','total_energy_kjmol','rg_center_norm','rdf_first_peak_height', 'hbond_dynamic', 'hbond_static']

random_seed = 212
np.random.seed(random_seed)

### 1.1 DFT+MD

In [6]:
### PTT DFT+MD
feature_cols = DFT_cols + MD_cols

target_col = 'PTT_bin'

# 只保留实际存在的列
existing_feature_cols = [col for col in feature_cols if col in data_PTT.columns]
missing_cols = [col for col in feature_cols if col not in data_PTT.columns]

print("存在的特征列数:", len(existing_feature_cols))
print("缺失的列:", missing_cols)

# 提取数据
X = data_PTT[existing_feature_cols].copy()
y = data_PTT[target_col].copy()

# 2. 自动去掉非数值列
# =========================
non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
if len(non_numeric_cols) > 0:
    print("\n以下列不是数值列，将被移除：")
    print(non_numeric_cols)

X = X.select_dtypes(include=[np.number]).copy()

print("\n最终用于建模的特征数:", X.shape[1])
print("最终特征列:")
print(X.columns.tolist())

# =========================
# 3. 标签编码
# strong -> 1, weak -> 0
# =========================
y = y.map({'strong': 1, 'weak': 0})

# 检查是否有未映射成功的标签
if y.isnull().any():
    raise ValueError("PTT_bin 中存在不是 'strong' 或 'weak' 的标签，请检查数据。")

print("\n标签分布：")
print(y.value_counts())
# =========================
# 4. 定义五折分层交叉验证
# =========================
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_seed)

# =========================
# 5. 定义模型管道
# =========================
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('rf', RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=random_seed,
        n_jobs=-1,
        class_weight='balanced'
    ))
])

# =========================
# 6. 交叉验证评估
# =========================
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_results = cross_validate(
    pipeline,
    X,
    y,
    cv=skf,
    scoring=scoring,
    return_train_score=False,
    n_jobs=-1
)

print("\n===== 5-Fold Cross Validation Results =====")
for metric in scoring.keys():
    scores = cv_results[f'test_{metric}']
    print(f"{metric:10s}: {scores.mean():.4f} ± {scores.std():.4f}")

# =========================
# 7. 获取交叉验证整体预测结果
# =========================
y_pred = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict',
    n_jobs=-1
)

y_proba = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# =========================
# 8. 输出整体指标
# =========================
print("\n===== Overall CV Prediction Metrics =====")
print("Accuracy :", accuracy_score(y, y_pred))
print("Precision:", precision_score(y, y_pred))
print("Recall   :", recall_score(y, y_pred))
print("F1-score :", f1_score(y, y_pred))
print("ROC-AUC  :", roc_auc_score(y, y_proba))

print("\n===== Confusion Matrix =====")
print(confusion_matrix(y, y_pred))

print("\n===== Classification Report =====")
print(classification_report(y, y_pred, target_names=['weak', 'strong']))

# ====================================================================================================
# 7. 模型调参 + 十折分层交叉验证
# ====================================================================================================
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import StratifiedKFold, GridSearchCV, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

from xgboost import XGBClassifier


# =========================
# 7.1 十折分层交叉验证设置
# =========================
skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=random_seed
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

# 调参时以 F1-score 作为主指标
refit_metric = "f1"


# =========================
# 7.2 类别不平衡处理
# =========================
n_pos = np.sum(y == 1)
n_neg = np.sum(y == 0)

if n_pos == 0 or n_neg == 0:
    raise ValueError("y 中必须同时包含 strong 和 weak 两类。")

scale_pos_weight = n_neg / n_pos

print("\n类别分布:")
print(y.value_counts())
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.4f}")


# =========================
# 7.3 定义模型和较小的参数搜索空间
# =========================
models_and_params = {
    "RandomForest": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", RandomForestClassifier(
                random_state=random_seed,
                n_jobs=-1,
                class_weight="balanced"
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [None, 5, 10],
            "model__min_samples_leaf": [1, 2],
            "model__max_features": ["sqrt", 0.5]
        }
    },

    "XGBoost": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=random_seed,
                n_jobs=-1,
                scale_pos_weight=scale_pos_weight
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [2, 3],
            "model__learning_rate": [0.03, 0.1],
            "model__subsample": [0.8, 1.0],
            "model__colsample_bytree": [0.8, 1.0]
        }
    },

    "MLP": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                random_state=random_seed,
                max_iter=1000,
                early_stopping=True
            ))
        ]),
        "param_grid": {
            "model__hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "model__alpha": [1e-4, 1e-3],
            "model__learning_rate_init": [1e-3, 5e-4]
        }
    },

    "LogisticRegression": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(
                random_state=random_seed,
                class_weight="balanced",
                max_iter=2000
            ))
        ]),
        "param_grid": {
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 10],
            "model__solver": ["liblinear"]
        }
    }
}


# =========================
# 7.4 对每个模型进行 GridSearchCV
# =========================
best_estimators = {}
summary_results = []

for model_name, item in models_and_params.items():

    print("\n" + "=" * 80)
    print(f"Start Grid Search for: {model_name}")
    print("=" * 80)

    grid_search = GridSearchCV(
        estimator=item["pipeline"],
        param_grid=item["param_grid"],
        scoring=scoring,
        refit=refit_metric,
        cv=skf,
        n_jobs=-1,
        return_train_score=False
    )

    grid_search.fit(X, y)

    best_estimators[model_name] = grid_search.best_estimator_

    print(f"\nBest parameters for {model_name}:")
    print(grid_search.best_params_)

    print(f"\nBest mean CV {refit_metric}: {grid_search.best_score_:.4f}")

    best_idx = grid_search.best_index_

    result_row = {
        "Model": model_name,
        "Best_Params": grid_search.best_params_
    }

    for metric in scoring.keys():
        mean_score = grid_search.cv_results_[f"mean_test_{metric}"][best_idx]
        std_score = grid_search.cv_results_[f"std_test_{metric}"][best_idx]

        result_row[f"{metric}_mean"] = mean_score
        result_row[f"{metric}_std"] = std_score

        print(f"{metric:10s}: {mean_score:.4f} ± {std_score:.4f}")

    summary_results.append(result_row)


# =========================
# 7.5 汇总不同模型的调参结果
# =========================
summary_df = pd.DataFrame(summary_results)

display_cols = [
    "Model",
    "accuracy_mean", "accuracy_std",
    "precision_mean", "precision_std",
    "recall_mean", "recall_std",
    "f1_mean", "f1_std",
    "roc_auc_mean", "roc_auc_std",
    "Best_Params"
]

summary_df = summary_df[display_cols]

print("\n" + "=" * 80)
print("Grid Search Summary")
print("=" * 80)
print(summary_df)


# =========================
# 8. 使用最佳模型进行整体交叉验证预测
# =========================
overall_results = []

for model_name, best_model in best_estimators.items():

    print("\n" + "=" * 80)
    print(f"Overall CV Prediction Metrics: {model_name}")
    print("=" * 80)

    y_pred = cross_val_predict(
        best_model,
        X,
        y,
        cv=skf,
        method="predict",
        n_jobs=-1
    )

    # 大多数模型都有 predict_proba
    if hasattr(best_model, "predict_proba"):
        y_proba = cross_val_predict(
            best_model,
            X,
            y,
            cv=skf,
            method="predict_proba",
            n_jobs=-1
        )[:, 1]
    else:
        y_proba = None

    acc = accuracy_score(y, y_pred)
    pre = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    if y_proba is not None:
        auc = roc_auc_score(y, y_proba)
    else:
        auc = np.nan

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {pre:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    print(f"ROC-AUC  : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y,
        y_pred,
        target_names=["weak", "strong"]
    ))

    overall_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": pre,
        "Recall": rec,
        "F1": f1,
        "ROC_AUC": auc
    })


# =========================
# 8.1 整体预测结果汇总
# =========================
overall_results_df = pd.DataFrame(overall_results)

print("\n" + "=" * 80)
print("Overall CV Prediction Summary")
print("=" * 80)
print(overall_results_df)


# =========================
# 8.2 选择最优模型
# =========================
best_model_name = overall_results_df.sort_values(
    by="F1",
    ascending=False
).iloc[0]["Model"]

best_model = best_estimators[best_model_name]

print("\n" + "=" * 80)
print(f"Best model based on overall CV F1-score: {best_model_name}")
print("=" * 80)

print("\nBest model pipeline:")
print(best_model)


df_dft_md_best_overall = overall_results_df[
    overall_results_df["Model"] == best_model_name
].copy()

df_dft_md_best_summary = pd.DataFrame({
    "method": ["DFT_MD"],
    "best_model": [best_model_name],
    "test_accuracy": [f"{df_dft_md_best_overall['Accuracy'].iloc[0]:.4f}"],
    "test_precision": [f"{df_dft_md_best_overall['Precision'].iloc[0]:.4f}"],
    "test_recall": [f"{df_dft_md_best_overall['Recall'].iloc[0]:.4f}"],
    "test_f1": [f"{df_dft_md_best_overall['F1'].iloc[0]:.4f}"],
    "test_roc_auc": [f"{df_dft_md_best_overall['ROC_AUC'].iloc[0]:.4f}"]
})

存在的特征列数: 21
缺失的列: []

最终用于建模的特征数: 21
最终特征列:
['es1_ev_high_pred', 'fs1_high_pred', 'et1_ev_high_pred', 'delta_est_ev_high_pred', 'min_abs_s1_tn_ev_high_pred', 'd_index_ang_high_pred', 't_index_ang_high_pred', 'zpe_ha_pred', 'gcorr_ha_pred', 'alpha_iso_bohr3_pred', 's_vib_cal_molk_pred', 'svib_frac_pred', 'hlg_kjmol_high_pred', 'dipole_gs_debye_high_pred', 'ci_index', 'vdw_energy_kjmol', 'total_energy_kjmol', 'rg_center_norm', 'rdf_first_peak_height', 'hbond_dynamic', 'hbond_static']

标签分布：
PTT_bin
1    129
0    114
Name: count, dtype: int64

===== 5-Fold Cross Validation Results =====
accuracy  : 0.7600 ± 0.1093
precision : 0.7669 ± 0.0869
recall    : 0.7891 ± 0.1653
f1        : 0.7719 ± 0.1118
roc_auc   : 0.8270 ± 0.0944

===== Overall CV Prediction Metrics =====
Accuracy : 0.7613168724279835
Precision: 0.7669172932330827
Recall   : 0.7906976744186046
F1-score : 0.7786259541984732
ROC-AUC  : 0.8338093295253638

===== Confusion Matrix =====
[[ 83  31]
 [ 27 102]]

===== Classification Report =====
              precision    recall  f1-score   support

        weak       0.75      0.73      0.74       114
      strong       0.77      0.79      0.78       129

    accuracy                           0.76       243
   macro avg       0.76      0.76      0.76       243
weighted avg       0.76      0.76      0.76       243


类别分布:
PTT_bin
1    129
0    114
Name: count, dtype: int64
XGBoost scale_pos_weight: 0.8837

================================================================================
Start Grid Search for: RandomForest
================================================================================

Best parameters for RandomForest:
{'model__max_depth': None, 'model__max_features': 0.5, 'model__min_samples_leaf': 2, 'model__n_estimators': 300}

Best mean CV f1: 0.7849
accuracy  : 0.7725 ± 0.1246
precision : 0.7752 ± 0.1089
recall    : 0.8122 ± 0.1832
f1        : 0.7849 ± 0.1271
roc_auc   : 0.8250 ± 0.1041

================================================================================
Start Grid Search for: XGBoost
================================================================================

Best parameters for XGBoost:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 2, 'model__n_estimators': 100, 'model__subsample': 1.0}

Best mean CV f1: 0.7785
accuracy  : 0.7603 ± 0.1151
precision : 0.7558 ± 0.1009
recall    : 0.8122 ± 0.1552
f1        : 0.7785 ± 0.1146
roc_auc   : 0.8092 ± 0.1024

================================================================================
Start Grid Search for: MLP
================================================================================

Best parameters for MLP:
{'model__alpha': 0.0001, 'model__hidden_layer_sizes': (128,), 'model__learning_rate_init': 0.001}

Best mean CV f1: 0.7681
accuracy  : 0.7278 ± 0.0765
precision : 0.7012 ± 0.0536
recall    : 0.8532 ± 0.0996
f1        : 0.7681 ± 0.0662
roc_auc   : 0.7651 ± 0.1306

================================================================================
Start Grid Search for: LogisticRegression
================================================================================

Best parameters for LogisticRegression:
{'model__C': 10, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

Best mean CV f1: 0.7656
accuracy  : 0.7528 ± 0.1118
precision : 0.7754 ± 0.1248
recall    : 0.7673 ± 0.1334
f1        : 0.7656 ± 0.1102
roc_auc   : 0.8100 ± 0.1033

================================================================================
Grid Search Summary
================================================================================
                Model  accuracy_mean  accuracy_std  precision_mean  \
0        RandomForest       0.772500      0.124607        0.775198
1             XGBoost       0.760333      0.115082        0.755774
2                 MLP       0.727833      0.076518        0.701155
3  LogisticRegression       0.752833      0.111804        0.775417

   precision_std  recall_mean  recall_std   f1_mean    f1_std  roc_auc_mean  \
0       0.108947     0.812179    0.183204  0.784935  0.127124      0.824985
1       0.100937     0.812179    0.155230  0.778475  0.114639      0.809222
2       0.053613     0.853205    0.099574  0.768064  0.066222      0.765059
3       0.124832     0.767308    0.133360  0.765553  0.110209      0.809984

   roc_auc_std                                        Best_Params
0     0.104129  {'model__max_depth': None, 'model__max_feature...
1     0.102446  {'model__colsample_bytree': 0.8, 'model__learn...
2     0.130648  {'model__alpha': 0.0001, 'model__hidden_layer_...
3     0.103294  {'model__C': 10, 'model__penalty': 'l1', 'mode...

================================================================================
Overall CV Prediction Metrics: RandomForest
================================================================================
Accuracy : 0.7737
Precision: 0.7721
Recall   : 0.8140
F1-score : 0.7925
ROC-AUC  : 0.8365

Confusion Matrix:
[[ 83  31]
 [ 24 105]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.78      0.73      0.75       114
      strong       0.77      0.81      0.79       129

    accuracy                           0.77       243
   macro avg       0.77      0.77      0.77       243
weighted avg       0.77      0.77      0.77       243


================================================================================
Overall CV Prediction Metrics: XGBoost
================================================================================
Accuracy : 0.7613
Precision: 0.7554
Recall   : 0.8140
F1-score : 0.7836
ROC-AUC  : 0.8138

Confusion Matrix:
[[ 80  34]
 [ 24 105]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.77      0.70      0.73       114
      strong       0.76      0.81      0.78       129

    accuracy                           0.76       243
   macro avg       0.76      0.76      0.76       243
weighted avg       0.76      0.76      0.76       243


================================================================================
Overall CV Prediction Metrics: MLP
================================================================================
Accuracy : 0.7284
Precision: 0.7006
Recall   : 0.8527
F1-score : 0.7692
ROC-AUC  : 0.7656

Confusion Matrix:
[[ 67  47]
 [ 19 110]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.78      0.59      0.67       114
      strong       0.70      0.85      0.77       129

    accuracy                           0.73       243
   macro avg       0.74      0.72      0.72       243
weighted avg       0.74      0.73      0.72       243


================================================================================
Overall CV Prediction Metrics: LogisticRegression
================================================================================
Accuracy : 0.7531
Precision: 0.7674
Recall   : 0.7674
F1-score : 0.7674
ROC-AUC  : 0.8120

Confusion Matrix:
[[84 30]
 [30 99]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.74      0.74      0.74       114
      strong       0.77      0.77      0.77       129

    accuracy                           0.75       243
   macro avg       0.75      0.75      0.75       243
weighted avg       0.75      0.75      0.75       243


================================================================================
Overall CV Prediction Summary
================================================================================
                Model  Accuracy  Precision    Recall        F1   ROC_AUC
0        RandomForest  0.773663   0.772059  0.813953  0.792453  0.836461
1             XGBoost  0.761317   0.755396  0.813953  0.783582  0.813783
2                 MLP  0.728395   0.700637  0.852713  0.769231  0.765606
3  LogisticRegression  0.753086   0.767442  0.767442  0.767442  0.812050

================================================================================
Best model based on overall CV F1-score: RandomForest
================================================================================

Best model pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        max_features=0.5, min_samples_leaf=2,
                                        n_estimators=300, n_jobs=-1,
                                        random_state=212))])

### 1.2 DFT

In [10]:
##################################################  PTT DFT  ###################################################
feature_cols = DFT_cols

target_col = 'PTT_bin'

# 只保留实际存在的列
existing_feature_cols = [col for col in feature_cols if col in data_PTT.columns]
missing_cols = [col for col in feature_cols if col not in data_PTT.columns]

print("存在的特征列数:", len(existing_feature_cols))
print("缺失的列:", missing_cols)

# 提取数据
X = data_PTT[existing_feature_cols].copy()
y = data_PTT[target_col].copy()

# 2. 自动去掉非数值列
# =========================
non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
if len(non_numeric_cols) > 0:
    print("\n以下列不是数值列，将被移除：")
    print(non_numeric_cols)

X = X.select_dtypes(include=[np.number]).copy()

print("\n最终用于建模的特征数:", X.shape[1])
print("最终特征列:")
print(X.columns.tolist())

# =========================
# 3. 标签编码
# strong -> 1, weak -> 0
# =========================
y = y.map({'strong': 1, 'weak': 0})

# 检查是否有未映射成功的标签
if y.isnull().any():
    raise ValueError("PTT_bin 中存在不是 'strong' 或 'weak' 的标签，请检查数据。")

print("\n标签分布：")
print(y.value_counts())
# =========================
# 4. 定义五折分层交叉验证
# =========================
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_seed)

# =========================
# 5. 定义模型管道
# =========================
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('rf', RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=random_seed,
        n_jobs=-1,
        class_weight='balanced'
    ))
])

# =========================
# 6. 交叉验证评估
# =========================
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_results = cross_validate(
    pipeline,
    X,
    y,
    cv=skf,
    scoring=scoring,
    return_train_score=False,
    n_jobs=-1
)

print("\n===== 5-Fold Cross Validation Results =====")
for metric in scoring.keys():
    scores = cv_results[f'test_{metric}']
    print(f"{metric:10s}: {scores.mean():.4f} ± {scores.std():.4f}")

# =========================
# 7. 获取交叉验证整体预测结果
# =========================
y_pred = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict',
    n_jobs=-1
)

y_proba = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# =========================
# 8. 输出整体指标
# =========================
print("\n===== Overall CV Prediction Metrics =====")
print("Accuracy :", accuracy_score(y, y_pred))
print("Precision:", precision_score(y, y_pred))
print("Recall   :", recall_score(y, y_pred))
print("F1-score :", f1_score(y, y_pred))
print("ROC-AUC  :", roc_auc_score(y, y_proba))

print("\n===== Confusion Matrix =====")
print(confusion_matrix(y, y_pred))

print("\n===== Classification Report =====")
print(classification_report(y, y_pred, target_names=['weak', 'strong']))

dft_10cv_results = cv_results
df_dft_10cv = pd.DataFrame(dft_10cv_results)

metric_cols = ['test_accuracy', 'test_precision', 'test_recall', 'test_f1', 'test_roc_auc']
mean_series = df_dft_10cv[metric_cols].mean()
std_series = df_dft_10cv[metric_cols].std()

df_dft_summary = pd.DataFrame({
    col: [f"{mean_series[col]:.4f}±{std_series[col]:.4f}"]
    for col in metric_cols
})

df_dft_summary.insert(0, 'method', 'DFT')

################################################## ####################################################

# =========================
# 7. 模型调参 + 十折分层交叉验证
# =========================

# =========================
# 7.1 十折分层交叉验证设置
# =========================
skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=random_seed
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

# 调参时以 F1-score 作为主指标
refit_metric = "f1"


# =========================
# 7.2 类别不平衡处理
# =========================
n_pos = np.sum(y == 1)
n_neg = np.sum(y == 0)

if n_pos == 0 or n_neg == 0:
    raise ValueError("y 中必须同时包含 strong 和 weak 两类。")

scale_pos_weight = n_neg / n_pos

print("\n类别分布:")
print(y.value_counts())
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.4f}")


# =========================
# 7.3 定义模型和较小的参数搜索空间
# =========================
models_and_params = {
    "RandomForest": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", RandomForestClassifier(
                random_state=random_seed,
                n_jobs=-1,
                class_weight="balanced"
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [None, 5, 10],
            "model__min_samples_leaf": [1, 2],
            "model__max_features": ["sqrt", 0.5]
        }
    },

    "XGBoost": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=random_seed,
                n_jobs=-1,
                scale_pos_weight=scale_pos_weight
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [2, 3],
            "model__learning_rate": [0.03, 0.1],
            "model__subsample": [0.8, 1.0],
            "model__colsample_bytree": [0.8, 1.0]
        }
    },

    "MLP": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                random_state=random_seed,
                max_iter=1000,
                early_stopping=True
            ))
        ]),
        "param_grid": {
            "model__hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "model__alpha": [1e-4, 1e-3],
            "model__learning_rate_init": [1e-3, 5e-4]
        }
    },

    "LogisticRegression": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(
                random_state=random_seed,
                class_weight="balanced",
                max_iter=2000
            ))
        ]),
        "param_grid": {
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 10],
            "model__solver": ["liblinear"]
        }
    }
}


# =========================
# 7.4 对每个模型进行 GridSearchCV
# =========================
best_estimators = {}
summary_results = []

for model_name, item in models_and_params.items():

    print("\n" + "=" * 80)
    print(f"Start Grid Search for: {model_name}")
    print("=" * 80)

    grid_search = GridSearchCV(
        estimator=item["pipeline"],
        param_grid=item["param_grid"],
        scoring=scoring,
        refit=refit_metric,
        cv=skf,
        n_jobs=-1,
        return_train_score=False
    )

    grid_search.fit(X, y)

    best_estimators[model_name] = grid_search.best_estimator_

    print(f"\nBest parameters for {model_name}:")
    print(grid_search.best_params_)

    print(f"\nBest mean CV {refit_metric}: {grid_search.best_score_:.4f}")

    best_idx = grid_search.best_index_

    result_row = {
        "Model": model_name,
        "Best_Params": grid_search.best_params_
    }

    for metric in scoring.keys():
        mean_score = grid_search.cv_results_[f"mean_test_{metric}"][best_idx]
        std_score = grid_search.cv_results_[f"std_test_{metric}"][best_idx]

        result_row[f"{metric}_mean"] = mean_score
        result_row[f"{metric}_std"] = std_score

        print(f"{metric:10s}: {mean_score:.4f} ± {std_score:.4f}")

    summary_results.append(result_row)


# =========================
# 7.5 汇总不同模型的调参结果
# =========================
summary_df = pd.DataFrame(summary_results)

display_cols = [
    "Model",
    "accuracy_mean", "accuracy_std",
    "precision_mean", "precision_std",
    "recall_mean", "recall_std",
    "f1_mean", "f1_std",
    "roc_auc_mean", "roc_auc_std",
    "Best_Params"
]

summary_df = summary_df[display_cols]

print("\n" + "=" * 80)
print("Grid Search Summary")
print("=" * 80)
print(summary_df)


# =========================
# 8. 使用最佳模型进行整体交叉验证预测
# =========================
overall_results = []

for model_name, best_model in best_estimators.items():

    print("\n" + "=" * 80)
    print(f"Overall CV Prediction Metrics: {model_name}")
    print("=" * 80)

    y_pred = cross_val_predict(
        best_model,
        X,
        y,
        cv=skf,
        method="predict",
        n_jobs=-1
    )

    # 大多数模型都有 predict_proba
    if hasattr(best_model, "predict_proba"):
        y_proba = cross_val_predict(
            best_model,
            X,
            y,
            cv=skf,
            method="predict_proba",
            n_jobs=-1
        )[:, 1]
    else:
        y_proba = None

    acc = accuracy_score(y, y_pred)
    pre = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    if y_proba is not None:
        auc = roc_auc_score(y, y_proba)
    else:
        auc = np.nan

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {pre:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    print(f"ROC-AUC  : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y,
        y_pred,
        target_names=["weak", "strong"]
    ))

    overall_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": pre,
        "Recall": rec,
        "F1": f1,
        "ROC_AUC": auc
    })


# =========================
# 8.1 整体预测结果汇总
# =========================
overall_results_df = pd.DataFrame(overall_results)

print("\n" + "=" * 80)
print("Overall CV Prediction Summary")
print("=" * 80)
print(overall_results_df)


# =========================
# 8.2 选择最优模型
# =========================
best_model_name = overall_results_df.sort_values(
    by="F1",
    ascending=False
).iloc[0]["Model"]

best_model = best_estimators[best_model_name]

print("\n" + "=" * 80)
print(f"Best model based on overall CV F1-score: {best_model_name}")
print("=" * 80)

print("\nBest model pipeline:")
print(best_model)

df_dft_best_overall = overall_results_df[
    overall_results_df["Model"] == best_model_name
].copy()

df_dft_best_summary = pd.DataFrame({
    "method": ["DFT"],
    "best_model": [best_model_name],
    "test_accuracy": [f"{df_dft_best_overall['Accuracy'].iloc[0]:.4f}"],
    "test_precision": [f"{df_dft_best_overall['Precision'].iloc[0]:.4f}"],
    "test_recall": [f"{df_dft_best_overall['Recall'].iloc[0]:.4f}"],
    "test_f1": [f"{df_dft_best_overall['F1'].iloc[0]:.4f}"],
    "test_roc_auc": [f"{df_dft_best_overall['ROC_AUC'].iloc[0]:.4f}"]
})

df_PTT_best_summary = pd.concat([df_dft_md_best_summary, df_dft_best_summary], ignore_index=True)

存在的特征列数: 15
缺失的列: []

最终用于建模的特征数: 15
最终特征列:
['es1_ev_high_pred', 'fs1_high_pred', 'et1_ev_high_pred', 'delta_est_ev_high_pred', 'min_abs_s1_tn_ev_high_pred', 'd_index_ang_high_pred', 't_index_ang_high_pred', 'zpe_ha_pred', 'gcorr_ha_pred', 'alpha_iso_bohr3_pred', 's_vib_cal_molk_pred', 'svib_frac_pred', 'hlg_kjmol_high_pred', 'dipole_gs_debye_high_pred', 'ci_index']

标签分布：
PTT_bin
1    129
0    114
Name: count, dtype: int64

===== 5-Fold Cross Validation Results =====
accuracy  : 0.7435 ± 0.1248
precision : 0.7513 ± 0.1125
recall    : 0.7814 ± 0.1531
f1        : 0.7614 ± 0.1176
roc_auc   : 0.8275 ± 0.0949

===== Overall CV Prediction Metrics =====
Accuracy : 0.7448559670781894
Precision: 0.7481481481481481
Recall   : 0.7829457364341085
F1-score : 0.7651515151515151
ROC-AUC  : 0.8314973480212159

===== Confusion Matrix =====
[[ 80  34]
 [ 28 101]]

===== Classification Report =====
              precision    recall  f1-score   support

        weak       0.74      0.70      0.72       114
      strong       0.75      0.78      0.77       129

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.74      0.74      0.74       243


类别分布:
PTT_bin
1    129
0    114
Name: count, dtype: int64
XGBoost scale_pos_weight: 0.8837

================================================================================
Start Grid Search for: RandomForest
================================================================================

Best parameters for RandomForest:
{'model__max_depth': None, 'model__max_features': 'sqrt', 'model__min_samples_leaf': 1, 'model__n_estimators': 300}

Best mean CV f1: 0.7614
accuracy  : 0.7435 ± 0.1248
precision : 0.7513 ± 0.1125
recall    : 0.7814 ± 0.1531
f1        : 0.7614 ± 0.1176
roc_auc   : 0.8275 ± 0.0949

================================================================================
Start Grid Search for: XGBoost
================================================================================

Best parameters for XGBoost:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.1, 'model__max_depth': 2, 'model__n_estimators': 300, 'model__subsample': 1.0}

Best mean CV f1: 0.7556
accuracy  : 0.7435 ± 0.0929
precision : 0.7496 ± 0.0764
recall    : 0.7731 ± 0.1581
f1        : 0.7556 ± 0.1025
roc_auc   : 0.8008 ± 0.0977

================================================================================
Start Grid Search for: MLP
================================================================================

Best parameters for MLP:
{'model__alpha': 0.0001, 'model__hidden_layer_sizes': (128,), 'model__learning_rate_init': 0.001}

Best mean CV f1: 0.7205
accuracy  : 0.7073 ± 0.0997
precision : 0.7260 ± 0.0958
recall    : 0.7282 ± 0.1518
f1        : 0.7205 ± 0.1041
roc_auc   : 0.7708 ± 0.0681

================================================================================
Start Grid Search for: LogisticRegression
================================================================================

Best parameters for LogisticRegression:
{'model__C': 10, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

Best mean CV f1: 0.7406
accuracy  : 0.7237 ± 0.1104
precision : 0.7445 ± 0.1082
recall    : 0.7449 ± 0.1233
f1        : 0.7406 ± 0.0994
roc_auc   : 0.8046 ± 0.1089

================================================================================
Grid Search Summary
================================================================================
                Model  accuracy_mean  accuracy_std  precision_mean  \
0        RandomForest       0.743500      0.124767        0.751334
1             XGBoost       0.743500      0.092857        0.749621
2                 MLP       0.707333      0.099658        0.726041
3  LogisticRegression       0.723667      0.110357        0.744498

   precision_std  recall_mean  recall_std   f1_mean    f1_std  roc_auc_mean  \
0       0.112503     0.781410    0.153055  0.761351  0.117606      0.827520
1       0.076436     0.773077    0.158067  0.755614  0.102542      0.800772
2       0.095784     0.728205    0.151781  0.720531  0.104141      0.770824
3       0.108228     0.744872    0.123297  0.740559  0.099386      0.804613

   roc_auc_std                                        Best_Params
0     0.094860  {'model__max_depth': None, 'model__max_feature...
1     0.097730  {'model__colsample_bytree': 1.0, 'model__learn...
2     0.068120  {'model__alpha': 0.0001, 'model__hidden_layer_...
3     0.108855  {'model__C': 10, 'model__penalty': 'l1', 'mode...

================================================================================
Overall CV Prediction Metrics: RandomForest
================================================================================
Accuracy : 0.7449
Precision: 0.7481
Recall   : 0.7829
F1-score : 0.7652
ROC-AUC  : 0.8315

Confusion Matrix:
[[ 80  34]
 [ 28 101]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.74      0.70      0.72       114
      strong       0.75      0.78      0.77       129

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.74      0.74      0.74       243


================================================================================
Overall CV Prediction Metrics: XGBoost
================================================================================
Accuracy : 0.7449
Precision: 0.7519
Recall   : 0.7752
F1-score : 0.7634
ROC-AUC  : 0.8044

Confusion Matrix:
[[ 81  33]
 [ 29 100]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.74      0.71      0.72       114
      strong       0.75      0.78      0.76       129

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.74      0.74      0.74       243


================================================================================
Overall CV Prediction Metrics: MLP
================================================================================
Accuracy : 0.7078
Precision: 0.7231
Recall   : 0.7287
F1-score : 0.7259
ROC-AUC  : 0.7680

Confusion Matrix:
[[78 36]
 [35 94]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.69      0.68      0.69       114
      strong       0.72      0.73      0.73       129

    accuracy                           0.71       243
   macro avg       0.71      0.71      0.71       243
weighted avg       0.71      0.71      0.71       243


================================================================================
Overall CV Prediction Metrics: LogisticRegression
================================================================================
Accuracy : 0.7243
Precision: 0.7385
Recall   : 0.7442
F1-score : 0.7413
ROC-AUC  : 0.8129

Confusion Matrix:
[[80 34]
 [33 96]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.71      0.70      0.70       114
      strong       0.74      0.74      0.74       129

    accuracy                           0.72       243
   macro avg       0.72      0.72      0.72       243
weighted avg       0.72      0.72      0.72       243


================================================================================
Overall CV Prediction Summary
================================================================================
                Model  Accuracy  Precision    Recall        F1   ROC_AUC
0        RandomForest  0.744856   0.748148  0.782946  0.765152  0.831497
1             XGBoost  0.744856   0.751880  0.775194  0.763359  0.804400
2                 MLP  0.707819   0.723077  0.728682  0.725869  0.767986
3  LogisticRegression  0.724280   0.738462  0.744186  0.741313  0.812865

================================================================================
Best model based on overall CV F1-score: RandomForest
================================================================================

Best model pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=300, n_jobs=-1,
                                        random_state=212))])

### 1.3 MD

In [12]:
##################################################  PTT MD  ###################################################
feature_cols = MD_cols

target_col = 'PTT_bin'

# 只保留实际存在的列
existing_feature_cols = [col for col in feature_cols if col in data_PTT.columns]
missing_cols = [col for col in feature_cols if col not in data_PTT.columns]

print("存在的特征列数:", len(existing_feature_cols))
print("缺失的列:", missing_cols)

# 提取数据
X = data_PTT[existing_feature_cols].copy()
y = data_PTT[target_col].copy()

# 2. 自动去掉非数值列
# =========================
non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
if len(non_numeric_cols) > 0:
    print("\n以下列不是数值列，将被移除：")
    print(non_numeric_cols)

X = X.select_dtypes(include=[np.number]).copy()

print("\n最终用于建模的特征数:", X.shape[1])
print("最终特征列:")
print(X.columns.tolist())

# =========================
# 3. 标签编码
# strong -> 1, weak -> 0
# =========================
y = y.map({'strong': 1, 'weak': 0})

# 检查是否有未映射成功的标签
if y.isnull().any():
    raise ValueError("PTT_bin 中存在不是 'strong' 或 'weak' 的标签，请检查数据。")

print("\n标签分布：")
print(y.value_counts())
# =========================
# 4. 定义五折分层交叉验证
# =========================
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_seed)

# =========================
# 5. 定义模型管道
# =========================
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('rf', RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=random_seed,
        n_jobs=-1,
        class_weight='balanced'
    ))
])

# =========================
# 6. 交叉验证评估
# =========================
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_results = cross_validate(
    pipeline,
    X,
    y,
    cv=skf,
    scoring=scoring,
    return_train_score=False,
    n_jobs=-1
)

print("\n===== 5-Fold Cross Validation Results =====")
for metric in scoring.keys():
    scores = cv_results[f'test_{metric}']
    print(f"{metric:10s}: {scores.mean():.4f} ± {scores.std():.4f}")

# =========================
# 7. 获取交叉验证整体预测结果
# =========================
y_pred = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict',
    n_jobs=-1
)

y_proba = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# =========================
# 8. 输出整体指标
# =========================
print("\n===== Overall CV Prediction Metrics =====")
print("Accuracy :", accuracy_score(y, y_pred))
print("Precision:", precision_score(y, y_pred))
print("Recall   :", recall_score(y, y_pred))
print("F1-score :", f1_score(y, y_pred))
print("ROC-AUC  :", roc_auc_score(y, y_proba))

print("\n===== Confusion Matrix =====")
print(confusion_matrix(y, y_pred))

print("\n===== Classification Report =====")
print(classification_report(y, y_pred, target_names=['weak', 'strong']))

dft_10cv_results = cv_results
df_dft_10cv = pd.DataFrame(dft_10cv_results)

metric_cols = ['test_accuracy', 'test_precision', 'test_recall', 'test_f1', 'test_roc_auc']
mean_series = df_dft_10cv[metric_cols].mean()
std_series = df_dft_10cv[metric_cols].std()

df_dft_summary = pd.DataFrame({
    col: [f"{mean_series[col]:.4f}±{std_series[col]:.4f}"]
    for col in metric_cols
})

df_dft_summary.insert(0, 'method', 'DFT')

################################################## ####################################################

# =========================
# 7. 模型调参 + 十折分层交叉验证
# =========================

# =========================
# 7.1 十折分层交叉验证设置
# =========================
skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=random_seed
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

# 调参时以 F1-score 作为主指标
refit_metric = "f1"


# =========================
# 7.2 类别不平衡处理
# =========================
n_pos = np.sum(y == 1)
n_neg = np.sum(y == 0)

if n_pos == 0 or n_neg == 0:
    raise ValueError("y 中必须同时包含 strong 和 weak 两类。")

scale_pos_weight = n_neg / n_pos

print("\n类别分布:")
print(y.value_counts())
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.4f}")


# =========================
# 7.3 定义模型和较小的参数搜索空间
# =========================
models_and_params = {
    "RandomForest": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", RandomForestClassifier(
                random_state=random_seed,
                n_jobs=-1,
                class_weight="balanced"
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [None, 5, 10],
            "model__min_samples_leaf": [1, 2],
            "model__max_features": ["sqrt", 0.5]
        }
    },

    "XGBoost": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=random_seed,
                n_jobs=-1,
                scale_pos_weight=scale_pos_weight
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [2, 3],
            "model__learning_rate": [0.03, 0.1],
            "model__subsample": [0.8, 1.0],
            "model__colsample_bytree": [0.8, 1.0]
        }
    },

    "MLP": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                random_state=random_seed,
                max_iter=1000,
                early_stopping=True
            ))
        ]),
        "param_grid": {
            "model__hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "model__alpha": [1e-4, 1e-3],
            "model__learning_rate_init": [1e-3, 5e-4]
        }
    },

    "LogisticRegression": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(
                random_state=random_seed,
                class_weight="balanced",
                max_iter=2000
            ))
        ]),
        "param_grid": {
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 10],
            "model__solver": ["liblinear"]
        }
    }
}


# =========================
# 7.4 对每个模型进行 GridSearchCV
# =========================
best_estimators = {}
summary_results = []

for model_name, item in models_and_params.items():

    print("\n" + "=" * 80)
    print(f"Start Grid Search for: {model_name}")
    print("=" * 80)

    grid_search = GridSearchCV(
        estimator=item["pipeline"],
        param_grid=item["param_grid"],
        scoring=scoring,
        refit=refit_metric,
        cv=skf,
        n_jobs=-1,
        return_train_score=False
    )

    grid_search.fit(X, y)

    best_estimators[model_name] = grid_search.best_estimator_

    print(f"\nBest parameters for {model_name}:")
    print(grid_search.best_params_)

    print(f"\nBest mean CV {refit_metric}: {grid_search.best_score_:.4f}")

    best_idx = grid_search.best_index_

    result_row = {
        "Model": model_name,
        "Best_Params": grid_search.best_params_
    }

    for metric in scoring.keys():
        mean_score = grid_search.cv_results_[f"mean_test_{metric}"][best_idx]
        std_score = grid_search.cv_results_[f"std_test_{metric}"][best_idx]

        result_row[f"{metric}_mean"] = mean_score
        result_row[f"{metric}_std"] = std_score

        print(f"{metric:10s}: {mean_score:.4f} ± {std_score:.4f}")

    summary_results.append(result_row)


# =========================
# 7.5 汇总不同模型的调参结果
# =========================
summary_df = pd.DataFrame(summary_results)

display_cols = [
    "Model",
    "accuracy_mean", "accuracy_std",
    "precision_mean", "precision_std",
    "recall_mean", "recall_std",
    "f1_mean", "f1_std",
    "roc_auc_mean", "roc_auc_std",
    "Best_Params"
]

summary_df = summary_df[display_cols]

print("\n" + "=" * 80)
print("Grid Search Summary")
print("=" * 80)
print(summary_df)


# =========================
# 8. 使用最佳模型进行整体交叉验证预测
# =========================
overall_results = []

for model_name, best_model in best_estimators.items():

    print("\n" + "=" * 80)
    print(f"Overall CV Prediction Metrics: {model_name}")
    print("=" * 80)

    y_pred = cross_val_predict(
        best_model,
        X,
        y,
        cv=skf,
        method="predict",
        n_jobs=-1
    )

    # 大多数模型都有 predict_proba
    if hasattr(best_model, "predict_proba"):
        y_proba = cross_val_predict(
            best_model,
            X,
            y,
            cv=skf,
            method="predict_proba",
            n_jobs=-1
        )[:, 1]
    else:
        y_proba = None

    acc = accuracy_score(y, y_pred)
    pre = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    if y_proba is not None:
        auc = roc_auc_score(y, y_proba)
    else:
        auc = np.nan

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {pre:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    print(f"ROC-AUC  : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y,
        y_pred,
        target_names=["weak", "strong"]
    ))

    overall_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": pre,
        "Recall": rec,
        "F1": f1,
        "ROC_AUC": auc
    })


# =========================
# 8.1 整体预测结果汇总
# =========================
overall_results_df = pd.DataFrame(overall_results)

print("\n" + "=" * 80)
print("Overall CV Prediction Summary")
print("=" * 80)
print(overall_results_df)


# =========================
# 8.2 选择最优模型
# =========================
best_model_name = overall_results_df.sort_values(
    by="F1",
    ascending=False
).iloc[0]["Model"]

best_model = best_estimators[best_model_name]

print("\n" + "=" * 80)
print(f"Best model based on overall CV F1-score: {best_model_name}")
print("=" * 80)

print("\nBest model pipeline:")
print(best_model)

df_md_best_overall = overall_results_df[
    overall_results_df["Model"] == best_model_name
].copy()

df_md_best_summary = pd.DataFrame({
    "method": ["MD"],
    "best_model": [best_model_name],
    "test_accuracy": [f"{df_md_best_overall['Accuracy'].iloc[0]:.4f}"],
    "test_precision": [f"{df_md_best_overall['Precision'].iloc[0]:.4f}"],
    "test_recall": [f"{df_md_best_overall['Recall'].iloc[0]:.4f}"],
    "test_f1": [f"{df_md_best_overall['F1'].iloc[0]:.4f}"],
    "test_roc_auc": [f"{df_md_best_overall['ROC_AUC'].iloc[0]:.4f}"]
})

df_PTT_best_summary = pd.concat([df_dft_md_best_summary, df_dft_best_summary, df_md_best_summary], ignore_index=True)

存在的特征列数: 6
缺失的列: []

最终用于建模的特征数: 6
最终特征列:
['vdw_energy_kjmol', 'total_energy_kjmol', 'rg_center_norm', 'rdf_first_peak_height', 'hbond_dynamic', 'hbond_static']

标签分布：
PTT_bin
1    129
0    114
Name: count, dtype: int64

===== 5-Fold Cross Validation Results =====
accuracy  : 0.6695 ± 0.1254
precision : 0.6743 ± 0.1061
recall    : 0.7301 ± 0.1615
f1        : 0.6972 ± 0.1240
roc_auc   : 0.7304 ± 0.1221

===== Overall CV Prediction Metrics =====
Accuracy : 0.6707818930041153
Precision: 0.6762589928057554
Recall   : 0.7286821705426356
F1-score : 0.7014925373134329
ROC-AUC  : 0.7280361757105943

===== Confusion Matrix =====
[[69 45]
 [35 94]]

===== Classification Report =====
              precision    recall  f1-score   support

        weak       0.66      0.61      0.63       114
      strong       0.68      0.73      0.70       129

    accuracy                           0.67       243
   macro avg       0.67      0.67      0.67       243
weighted avg       0.67      0.67      0.67       243


类别分布:
PTT_bin
1    129
0    114
Name: count, dtype: int64
XGBoost scale_pos_weight: 0.8837

================================================================================
Start Grid Search for: RandomForest
================================================================================

Best parameters for RandomForest:
{'model__max_depth': 10, 'model__max_features': 0.5, 'model__min_samples_leaf': 2, 'model__n_estimators': 100}

Best mean CV f1: 0.7084
accuracy  : 0.6863 ± 0.1207
precision : 0.6980 ± 0.1085
recall    : 0.7295 ± 0.1500
f1        : 0.7084 ± 0.1187
roc_auc   : 0.7410 ± 0.1111

================================================================================
Start Grid Search for: XGBoost
================================================================================

Best parameters for XGBoost:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__n_estimators': 100, 'model__subsample': 0.8}

Best mean CV f1: 0.6968
accuracy  : 0.6903 ± 0.1196
precision : 0.7259 ± 0.1260
recall    : 0.6814 ± 0.1456
f1        : 0.6968 ± 0.1240
roc_auc   : 0.7445 ± 0.1219

================================================================================
Start Grid Search for: MLP
================================================================================

Best parameters for MLP:
{'model__alpha': 0.0001, 'model__hidden_layer_sizes': (64, 32), 'model__learning_rate_init': 0.001}

Best mean CV f1: 0.6936
accuracy  : 0.5310 ± 0.0142
precision : 0.5310 ± 0.0142
recall    : 1.0000 ± 0.0000
f1        : 0.6936 ± 0.0122
roc_auc   : 0.5805 ± 0.1141

================================================================================
Start Grid Search for: LogisticRegression
================================================================================

Best parameters for LogisticRegression:
{'model__C': 10, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

Best mean CV f1: 0.6598
accuracy  : 0.6740 ± 0.0936
precision : 0.7425 ± 0.1338
recall    : 0.6103 ± 0.1385
f1        : 0.6598 ± 0.1129
roc_auc   : 0.7123 ± 0.1108

================================================================================
Grid Search Summary
================================================================================
                Model  accuracy_mean  accuracy_std  precision_mean  \
0        RandomForest       0.686333      0.120651        0.697983
1             XGBoost       0.690333      0.119594        0.725874
2                 MLP       0.531000      0.014166        0.531000
3  LogisticRegression       0.674000      0.093563        0.742538

   precision_std  recall_mean  recall_std   f1_mean    f1_std  roc_auc_mean  \
0       0.108505     0.729487    0.150000  0.708446  0.118699      0.740997
1       0.126000     0.681410    0.145558  0.696784  0.124015      0.744542
2       0.014166     1.000000    0.000000  0.693551  0.012194      0.580507
3       0.133810     0.610256    0.138462  0.659768  0.112892      0.712320

   roc_auc_std                                        Best_Params
0     0.111065  {'model__max_depth': 10, 'model__max_features'...
1     0.121897  {'model__colsample_bytree': 0.8, 'model__learn...
2     0.114115  {'model__alpha': 0.0001, 'model__hidden_layer_...
3     0.110756  {'model__C': 10, 'model__penalty': 'l1', 'mode...

================================================================================
Overall CV Prediction Metrics: RandomForest
================================================================================
Accuracy : 0.6872
Precision: 0.6963
Recall   : 0.7287
F1-score : 0.7121
ROC-AUC  : 0.7330

Confusion Matrix:
[[73 41]
 [35 94]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.68      0.64      0.66       114
      strong       0.70      0.73      0.71       129

    accuracy                           0.69       243
   macro avg       0.69      0.68      0.68       243
weighted avg       0.69      0.69      0.69       243


================================================================================
Overall CV Prediction Metrics: XGBoost
================================================================================
Accuracy : 0.6914
Precision: 0.7213
Recall   : 0.6822
F1-score : 0.7012
ROC-AUC  : 0.7394

Confusion Matrix:
[[80 34]
 [41 88]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.66      0.70      0.68       114
      strong       0.72      0.68      0.70       129

    accuracy                           0.69       243
   macro avg       0.69      0.69      0.69       243
weighted avg       0.69      0.69      0.69       243


================================================================================
Overall CV Prediction Metrics: MLP
================================================================================
Accuracy : 0.5309
Precision: 0.5309
Recall   : 1.0000
F1-score : 0.6935
ROC-AUC  : 0.5732

Confusion Matrix:
[[  0 114]
 [  0 129]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.00      0.00      0.00       114
      strong       0.53      1.00      0.69       129

    accuracy                           0.53       243
   macro avg       0.27      0.50      0.35       243
weighted avg       0.28      0.53      0.37       243


================================================================================
Overall CV Prediction Metrics: LogisticRegression
================================================================================
Accuracy : 0.6749
Precision: 0.7315
Recall   : 0.6124
F1-score : 0.6667
ROC-AUC  : 0.7264

Confusion Matrix:
[[85 29]
 [50 79]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.63      0.75      0.68       114
      strong       0.73      0.61      0.67       129

    accuracy                           0.67       243
   macro avg       0.68      0.68      0.67       243
weighted avg       0.68      0.67      0.67       243


================================================================================
Overall CV Prediction Summary
================================================================================
                Model  Accuracy  Precision    Recall        F1   ROC_AUC
0        RandomForest  0.687243   0.696296  0.728682  0.712121  0.733034
1             XGBoost  0.691358   0.721311  0.682171  0.701195  0.739392
2                 MLP  0.530864   0.530864  1.000000  0.693548  0.573235
3  LogisticRegression  0.674897   0.731481  0.612403  0.666667  0.726438

================================================================================
Best model based on overall CV F1-score: RandomForest
================================================================================

Best model pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 RandomForestClassifier(class_weight='balanced', max_depth=10,
                                        max_features=0.5, min_samples_leaf=2,
                                        n_jobs=-1, random_state=212))])

In [13]:
df_PTT_best_summary

,method,best_model,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
0,DFT_MD,RandomForest,0.7737,0.7721,0.8140,0.7925,0.8365
1,DFT,RandomForest,0.7449,0.7481,0.7829,0.7652,0.8315
2,MD,RandomForest,0.6872,0.6963,0.7287,0.7121,0.7330

## 2. PDT

In [14]:
data_PDT["PDT_bin"] = data_PDT["photodynamic"].astype(str).replace({"middle": "weak"})
data_PDT['PDT_bin'].value_counts()

PDT_bin
strong    130
weak      113
Name: count, dtype: int64

### 2.1 DFT+MD

In [15]:
# =========================
# 1. 选择输入特征和标签
# =========================
feature_cols = DFT_cols + MD_cols

target_col = 'PDT_bin'

# 只保留实际存在的列
existing_feature_cols = [col for col in feature_cols if col in data_PDT.columns]
missing_cols = [col for col in feature_cols if col not in data_PDT.columns]

print("存在的特征列数:", len(existing_feature_cols))
print("缺失的列:", missing_cols)

# 提取数据
X = data_PDT[existing_feature_cols].copy()
y = data_PDT[target_col].copy()

# 2. 自动去掉非数值列
# =========================
non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
if len(non_numeric_cols) > 0:
    print("\n以下列不是数值列，将被移除：")
    print(non_numeric_cols)

X = X.select_dtypes(include=[np.number]).copy()

print("\n最终用于建模的特征数:", X.shape[1])
print("最终特征列:")
print(X.columns.tolist())

# =========================
# 3. 标签编码
# strong -> 1, weak -> 0
# =========================
y = y.map({'strong': 1, 'weak': 0})

# 检查是否有未映射成功的标签
if y.isnull().any():
    raise ValueError("PDT_bin 中存在不是 'strong' 或 'weak' 的标签，请检查数据。")

print("\n标签分布：")
print(y.value_counts())
# =========================
# 4. 定义五折分层交叉验证
# =========================
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_seed)

# =========================
# 5. 定义模型管道
# =========================
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('rf', RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=random_seed,
        n_jobs=-1,
        class_weight='balanced'
    ))
])

# =========================
# 6. 交叉验证评估
# =========================
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_results = cross_validate(
    pipeline,
    X,
    y,
    cv=skf,
    scoring=scoring,
    return_train_score=False,
    n_jobs=-1
)

print("\n===== 5-Fold Cross Validation Results =====")
for metric in scoring.keys():
    scores = cv_results[f'test_{metric}']
    print(f"{metric:10s}: {scores.mean():.4f} ± {scores.std():.4f}")

# =========================
# 7. 获取交叉验证整体预测结果
# =========================
y_pred = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict',
    n_jobs=-1
)

y_proba = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# =========================
# 8. 输出整体指标
# =========================
print("\n===== Overall CV Prediction Metrics =====")
print("Accuracy :", accuracy_score(y, y_pred))
print("Precision:", precision_score(y, y_pred))
print("Recall   :", recall_score(y, y_pred))
print("F1-score :", f1_score(y, y_pred))
print("ROC-AUC  :", roc_auc_score(y, y_proba))

print("\n===== Confusion Matrix =====")
print(confusion_matrix(y, y_pred))

print("\n===== Classification Report =====")
print(classification_report(y, y_pred, target_names=['weak', 'strong']))


################################### 调参 ########################################

# =========================
# 7. 模型调参 + 十折分层交叉验证
# =========================
# =========================
# 7.1 十折分层交叉验证设置
# =========================
skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=random_seed
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

# 调参时以 F1-score 作为主指标
refit_metric = "f1"


# =========================
# 7.2 类别不平衡处理
# =========================
n_pos = np.sum(y == 1)
n_neg = np.sum(y == 0)

if n_pos == 0 or n_neg == 0:
    raise ValueError("y 中必须同时包含 strong 和 weak 两类。")

scale_pos_weight = n_neg / n_pos

print("\n类别分布:")
print(y.value_counts())
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.4f}")


# =========================
# 7.3 定义模型和较小的参数搜索空间
# =========================
models_and_params = {
    "RandomForest": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", RandomForestClassifier(
                random_state=random_seed,
                n_jobs=-1,
                class_weight="balanced"
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [None, 5, 10],
            "model__min_samples_leaf": [1, 2],
            "model__max_features": ["sqrt", 0.5]
        }
    },

    "XGBoost": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=random_seed,
                n_jobs=-1,
                scale_pos_weight=scale_pos_weight
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [2, 3],
            "model__learning_rate": [0.03, 0.1],
            "model__subsample": [0.8, 1.0],
            "model__colsample_bytree": [0.8, 1.0]
        }
    },

    "MLP": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                random_state=random_seed,
                max_iter=1000,
                early_stopping=True
            ))
        ]),
        "param_grid": {
            "model__hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "model__alpha": [1e-4, 1e-3],
            "model__learning_rate_init": [1e-3, 5e-4]
        }
    },

    "LogisticRegression": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(
                random_state=random_seed,
                class_weight="balanced",
                max_iter=2000
            ))
        ]),
        "param_grid": {
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 10],
            "model__solver": ["liblinear"]
        }
    }
}


# =========================
# 7.4 对每个模型进行 GridSearchCV
# =========================
best_estimators = {}
summary_results = []

for model_name, item in models_and_params.items():

    print("\n" + "=" * 80)
    print(f"Start Grid Search for: {model_name}")
    print("=" * 80)

    grid_search = GridSearchCV(
        estimator=item["pipeline"],
        param_grid=item["param_grid"],
        scoring=scoring,
        refit=refit_metric,
        cv=skf,
        n_jobs=-1,
        return_train_score=False
    )

    grid_search.fit(X, y)

    best_estimators[model_name] = grid_search.best_estimator_

    print(f"\nBest parameters for {model_name}:")
    print(grid_search.best_params_)

    print(f"\nBest mean CV {refit_metric}: {grid_search.best_score_:.4f}")

    best_idx = grid_search.best_index_

    result_row = {
        "Model": model_name,
        "Best_Params": grid_search.best_params_
    }

    for metric in scoring.keys():
        mean_score = grid_search.cv_results_[f"mean_test_{metric}"][best_idx]
        std_score = grid_search.cv_results_[f"std_test_{metric}"][best_idx]

        result_row[f"{metric}_mean"] = mean_score
        result_row[f"{metric}_std"] = std_score

        print(f"{metric:10s}: {mean_score:.4f} ± {std_score:.4f}")

    summary_results.append(result_row)


# =========================
# 7.5 汇总不同模型的调参结果
# =========================
summary_df = pd.DataFrame(summary_results)

display_cols = [
    "Model",
    "accuracy_mean", "accuracy_std",
    "precision_mean", "precision_std",
    "recall_mean", "recall_std",
    "f1_mean", "f1_std",
    "roc_auc_mean", "roc_auc_std",
    "Best_Params"
]

summary_df = summary_df[display_cols]

print("\n" + "=" * 80)
print("Grid Search Summary")
print("=" * 80)
print(summary_df)


# =========================
# 8. 使用最佳模型进行整体交叉验证预测
# =========================
overall_results = []

for model_name, best_model in best_estimators.items():

    print("\n" + "=" * 80)
    print(f"Overall CV Prediction Metrics: {model_name}")
    print("=" * 80)

    y_pred = cross_val_predict(
        best_model,
        X,
        y,
        cv=skf,
        method="predict",
        n_jobs=-1
    )

    # 大多数模型都有 predict_proba
    if hasattr(best_model, "predict_proba"):
        y_proba = cross_val_predict(
            best_model,
            X,
            y,
            cv=skf,
            method="predict_proba",
            n_jobs=-1
        )[:, 1]
    else:
        y_proba = None

    acc = accuracy_score(y, y_pred)
    pre = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    if y_proba is not None:
        auc = roc_auc_score(y, y_proba)
    else:
        auc = np.nan

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {pre:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    print(f"ROC-AUC  : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y,
        y_pred,
        target_names=["weak", "strong"]
    ))

    overall_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": pre,
        "Recall": rec,
        "F1": f1,
        "ROC_AUC": auc
    })


# =========================
# 8.1 整体预测结果汇总
# =========================
overall_results_df = pd.DataFrame(overall_results)

print("\n" + "=" * 80)
print("Overall CV Prediction Summary")
print("=" * 80)
print(overall_results_df)


# =========================
# 8.2 选择最优模型
# =========================
best_model_name = overall_results_df.sort_values(
    by="F1",
    ascending=False
).iloc[0]["Model"]

best_model = best_estimators[best_model_name]

print("\n" + "=" * 80)
print(f"Best model based on overall CV F1-score: {best_model_name}")
print("=" * 80)

print("\nBest model pipeline:")
print(best_model)

df_PDT_dft_md_best_overall = overall_results_df[
    overall_results_df["Model"] == best_model_name
].copy()

df_PDT_dft_md_best_summary = pd.DataFrame({
    "method": ["DFT_MD"],
    "best_model": [best_model_name],
    "test_accuracy": [f"{df_PDT_dft_md_best_overall['Accuracy'].iloc[0]:.4f}"],
    "test_precision": [f"{df_PDT_dft_md_best_overall['Precision'].iloc[0]:.4f}"],
    "test_recall": [f"{df_PDT_dft_md_best_overall['Recall'].iloc[0]:.4f}"],
    "test_f1": [f"{df_PDT_dft_md_best_overall['F1'].iloc[0]:.4f}"],
    "test_roc_auc": [f"{df_PDT_dft_md_best_overall['ROC_AUC'].iloc[0]:.4f}"]
})

存在的特征列数: 21
缺失的列: []

最终用于建模的特征数: 21
最终特征列:
['es1_ev_high_pred', 'fs1_high_pred', 'et1_ev_high_pred', 'delta_est_ev_high_pred', 'min_abs_s1_tn_ev_high_pred', 'd_index_ang_high_pred', 't_index_ang_high_pred', 'zpe_ha_pred', 'gcorr_ha_pred', 'alpha_iso_bohr3_pred', 's_vib_cal_molk_pred', 'svib_frac_pred', 'hlg_kjmol_high_pred', 'dipole_gs_debye_high_pred', 'ci_index', 'vdw_energy_kjmol', 'total_energy_kjmol', 'rg_center_norm', 'rdf_first_peak_height', 'hbond_dynamic', 'hbond_static']

标签分布：
PDT_bin
1    130
0    113
Name: count, dtype: int64

===== 5-Fold Cross Validation Results =====
accuracy  : 0.7202 ± 0.0981
precision : 0.7514 ± 0.0988
recall    : 0.7231 ± 0.1250
f1        : 0.7320 ± 0.0960
roc_auc   : 0.8085 ± 0.0797

===== Overall CV Prediction Metrics =====
Accuracy : 0.720164609053498
Precision: 0.746031746031746
Recall   : 0.7230769230769231
F1-score : 0.734375
ROC-AUC  : 0.8014976174268209

===== Confusion Matrix =====
[[81 32]
 [36 94]]

===== Classification Report =====
              precision    recall  f1-score   support

        weak       0.69      0.72      0.70       113
      strong       0.75      0.72      0.73       130

    accuracy                           0.72       243
   macro avg       0.72      0.72      0.72       243
weighted avg       0.72      0.72      0.72       243


类别分布:
PDT_bin
1    130
0    113
Name: count, dtype: int64
XGBoost scale_pos_weight: 0.8692

================================================================================
Start Grid Search for: RandomForest
================================================================================

Best parameters for RandomForest:
{'model__max_depth': 10, 'model__max_features': 0.5, 'model__min_samples_leaf': 2, 'model__n_estimators': 100}

Best mean CV f1: 0.7570
accuracy  : 0.7448 ± 0.0853
precision : 0.7690 ± 0.0777
recall    : 0.7538 ± 0.1231
f1        : 0.7570 ± 0.0832
roc_auc   : 0.8121 ± 0.0807

================================================================================
Start Grid Search for: XGBoost
================================================================================

Best parameters for XGBoost:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__n_estimators': 100, 'model__subsample': 1.0}

Best mean CV f1: 0.7295
accuracy  : 0.7362 ± 0.0581
precision : 0.8041 ± 0.0576
recall    : 0.6769 ± 0.1077
f1        : 0.7295 ± 0.0696
roc_auc   : 0.8036 ± 0.0895

================================================================================
Start Grid Search for: MLP
================================================================================

Best parameters for MLP:
{'model__alpha': 0.0001, 'model__hidden_layer_sizes': (128,), 'model__learning_rate_init': 0.0005}

Best mean CV f1: 0.7048
accuracy  : 0.5967 ± 0.0481
precision : 0.5814 ± 0.0336
recall    : 0.9000 ± 0.0692
f1        : 0.7048 ± 0.0313
roc_auc   : 0.6785 ± 0.0764

================================================================================
Start Grid Search for: LogisticRegression
================================================================================

Best parameters for LogisticRegression:
{'model__C': 1, 'model__penalty': 'l2', 'model__solver': 'liblinear'}

Best mean CV f1: 0.7169
accuracy  : 0.7200 ± 0.0663
precision : 0.7892 ± 0.1019
recall    : 0.6692 ± 0.1035
f1        : 0.7169 ± 0.0706
roc_auc   : 0.7917 ± 0.0820

================================================================================
Grid Search Summary
================================================================================
                Model  accuracy_mean  accuracy_std  precision_mean  \
0        RandomForest       0.744833      0.085302        0.769047
1             XGBoost       0.736167      0.058114        0.804081
2                 MLP       0.596667      0.048051        0.581383
3  LogisticRegression       0.720000      0.066253        0.789203

   precision_std  recall_mean  recall_std   f1_mean    f1_std  roc_auc_mean  \
0       0.077702     0.753846    0.123077  0.756982  0.083234      0.812063
1       0.057601     0.676923    0.107692  0.729458  0.069557      0.803555
2       0.033575     0.900000    0.069231  0.704769  0.031270      0.678497
3       0.101858     0.669231    0.103489  0.716851  0.070626      0.791725

   roc_auc_std                                        Best_Params
0     0.080660  {'model__max_depth': 10, 'model__max_features'...
1     0.089529  {'model__colsample_bytree': 1.0, 'model__learn...
2     0.076374  {'model__alpha': 0.0001, 'model__hidden_layer_...
3     0.081992  {'model__C': 1, 'model__penalty': 'l2', 'model...

================================================================================
Overall CV Prediction Metrics: RandomForest
================================================================================
Accuracy : 0.7449
Precision: 0.7656
Recall   : 0.7538
F1-score : 0.7597
ROC-AUC  : 0.8049

Confusion Matrix:
[[83 30]
 [32 98]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.72      0.73      0.73       113
      strong       0.77      0.75      0.76       130

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.75      0.74      0.74       243


================================================================================
Overall CV Prediction Metrics: XGBoost
================================================================================
Accuracy : 0.7366
Precision: 0.8000
Recall   : 0.6769
F1-score : 0.7333
ROC-AUC  : 0.7938

Confusion Matrix:
[[91 22]
 [42 88]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.68      0.81      0.74       113
      strong       0.80      0.68      0.73       130

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.75      0.74      0.74       243


================================================================================
Overall CV Prediction Metrics: MLP
================================================================================
Accuracy : 0.5967
Precision: 0.5792
Recall   : 0.9000
F1-score : 0.7048
ROC-AUC  : 0.6651

Confusion Matrix:
[[ 28  85]
 [ 13 117]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.68      0.25      0.36       113
      strong       0.58      0.90      0.70       130

    accuracy                           0.60       243
   macro avg       0.63      0.57      0.53       243
weighted avg       0.63      0.60      0.55       243


================================================================================
Overall CV Prediction Metrics: LogisticRegression
================================================================================
Accuracy : 0.7202
Precision: 0.7768
Recall   : 0.6692
F1-score : 0.7190
ROC-AUC  : 0.7807

Confusion Matrix:
[[88 25]
 [43 87]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.67      0.78      0.72       113
      strong       0.78      0.67      0.72       130

    accuracy                           0.72       243
   macro avg       0.72      0.72      0.72       243
weighted avg       0.73      0.72      0.72       243


================================================================================
Overall CV Prediction Summary
================================================================================
                Model  Accuracy  Precision    Recall        F1   ROC_AUC
0        RandomForest  0.744856   0.765625  0.753846  0.759690  0.804901
1             XGBoost  0.736626   0.800000  0.676923  0.733333  0.793771
2                 MLP  0.596708   0.579208  0.900000  0.704819  0.665078
3  LogisticRegression  0.720165   0.776786  0.669231  0.719008  0.780667

================================================================================
Best model based on overall CV F1-score: RandomForest
================================================================================

Best model pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 RandomForestClassifier(class_weight='balanced', max_depth=10,
                                        max_features=0.5, min_samples_leaf=2,
                                        n_jobs=-1, random_state=212))])

### 2.2 DFT

In [16]:
########################################### DFT #####################################################

# =========================
# 1. 选择输入特征和标签
# =========================
feature_cols = DFT_cols

target_col = 'PDT_bin'

# 只保留实际存在的列
existing_feature_cols = [col for col in feature_cols if col in data_PDT.columns]
missing_cols = [col for col in feature_cols if col not in data_PDT.columns]

print("存在的特征列数:", len(existing_feature_cols))
print("缺失的列:", missing_cols)

# 提取数据
X = data_PDT[existing_feature_cols].copy()
y = data_PDT[target_col].copy()

# 2. 自动去掉非数值列
# =========================
non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
if len(non_numeric_cols) > 0:
    print("\n以下列不是数值列，将被移除：")
    print(non_numeric_cols)

X = X.select_dtypes(include=[np.number]).copy()

print("\n最终用于建模的特征数:", X.shape[1])
print("最终特征列:")
print(X.columns.tolist())

# =========================
# 3. 标签编码
# strong -> 1, weak -> 0
# =========================
y = y.map({'strong': 1, 'weak': 0})

# 检查是否有未映射成功的标签
if y.isnull().any():
    raise ValueError("PDT_bin 中存在不是 'strong' 或 'weak' 的标签，请检查数据。")

print("\n标签分布：")
print(y.value_counts())
# =========================
# 4. 定义五折分层交叉验证
# =========================
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_seed)

# =========================
# 5. 定义模型管道
# =========================
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('rf', RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=random_seed,
        n_jobs=-1,
        class_weight='balanced'
    ))
])

# =========================
# 6. 交叉验证评估
# =========================
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_results = cross_validate(
    pipeline,
    X,
    y,
    cv=skf,
    scoring=scoring,
    return_train_score=False,
    n_jobs=-1
)

print("\n===== 5-Fold Cross Validation Results =====")
for metric in scoring.keys():
    scores = cv_results[f'test_{metric}']
    print(f"{metric:10s}: {scores.mean():.4f} ± {scores.std():.4f}")

# =========================
# 7. 获取交叉验证整体预测结果
# =========================
y_pred = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict',
    n_jobs=-1
)

y_proba = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# =========================
# 8. 输出整体指标
# =========================
print("\n===== Overall CV Prediction Metrics =====")
print("Accuracy :", accuracy_score(y, y_pred))
print("Precision:", precision_score(y, y_pred))
print("Recall   :", recall_score(y, y_pred))
print("F1-score :", f1_score(y, y_pred))
print("ROC-AUC  :", roc_auc_score(y, y_proba))

print("\n===== Confusion Matrix =====")
print(confusion_matrix(y, y_pred))

print("\n===== Classification Report =====")
print(classification_report(y, y_pred, target_names=['weak', 'strong']))


#################################### 调参 ########################################

# =========================
# 7. 模型调参 + 十折分层交叉验证
# =========================
# =========================
# 7.1 十折分层交叉验证设置
# =========================
skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=random_seed
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

# 调参时以 F1-score 作为主指标
refit_metric = "f1"


# =========================
# 7.2 类别不平衡处理
# =========================
n_pos = np.sum(y == 1)
n_neg = np.sum(y == 0)

if n_pos == 0 or n_neg == 0:
    raise ValueError("y 中必须同时包含 strong 和 weak 两类。")

scale_pos_weight = n_neg / n_pos

print("\n类别分布:")
print(y.value_counts())
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.4f}")


# =========================
# 7.3 定义模型和较小的参数搜索空间
# =========================
models_and_params = {
    "RandomForest": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", RandomForestClassifier(
                random_state=random_seed,
                n_jobs=-1,
                class_weight="balanced"
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [None, 5, 10],
            "model__min_samples_leaf": [1, 2],
            "model__max_features": ["sqrt", 0.5]
        }
    },

    "XGBoost": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=random_seed,
                n_jobs=-1,
                scale_pos_weight=scale_pos_weight
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [2, 3],
            "model__learning_rate": [0.03, 0.1],
            "model__subsample": [0.8, 1.0],
            "model__colsample_bytree": [0.8, 1.0]
        }
    },

    "MLP": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                random_state=random_seed,
                max_iter=1000,
                early_stopping=True
            ))
        ]),
        "param_grid": {
            "model__hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "model__alpha": [1e-4, 1e-3],
            "model__learning_rate_init": [1e-3, 5e-4]
        }
    },

    "LogisticRegression": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(
                random_state=random_seed,
                class_weight="balanced",
                max_iter=2000
            ))
        ]),
        "param_grid": {
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 10],
            "model__solver": ["liblinear"]
        }
    }
}


# =========================
# 7.4 对每个模型进行 GridSearchCV
# =========================
best_estimators = {}
summary_results = []

for model_name, item in models_and_params.items():

    print("\n" + "=" * 80)
    print(f"Start Grid Search for: {model_name}")
    print("=" * 80)

    grid_search = GridSearchCV(
        estimator=item["pipeline"],
        param_grid=item["param_grid"],
        scoring=scoring,
        refit=refit_metric,
        cv=skf,
        n_jobs=-1,
        return_train_score=False
    )

    grid_search.fit(X, y)

    best_estimators[model_name] = grid_search.best_estimator_

    print(f"\nBest parameters for {model_name}:")
    print(grid_search.best_params_)

    print(f"\nBest mean CV {refit_metric}: {grid_search.best_score_:.4f}")

    best_idx = grid_search.best_index_

    result_row = {
        "Model": model_name,
        "Best_Params": grid_search.best_params_
    }

    for metric in scoring.keys():
        mean_score = grid_search.cv_results_[f"mean_test_{metric}"][best_idx]
        std_score = grid_search.cv_results_[f"std_test_{metric}"][best_idx]

        result_row[f"{metric}_mean"] = mean_score
        result_row[f"{metric}_std"] = std_score

        print(f"{metric:10s}: {mean_score:.4f} ± {std_score:.4f}")

    summary_results.append(result_row)


# =========================
# 7.5 汇总不同模型的调参结果
# =========================
summary_df = pd.DataFrame(summary_results)

display_cols = [
    "Model",
    "accuracy_mean", "accuracy_std",
    "precision_mean", "precision_std",
    "recall_mean", "recall_std",
    "f1_mean", "f1_std",
    "roc_auc_mean", "roc_auc_std",
    "Best_Params"
]

summary_df = summary_df[display_cols]

print("\n" + "=" * 80)
print("Grid Search Summary")
print("=" * 80)
print(summary_df)


# =========================
# 8. 使用最佳模型进行整体交叉验证预测
# =========================
overall_results = []

for model_name, best_model in best_estimators.items():

    print("\n" + "=" * 80)
    print(f"Overall CV Prediction Metrics: {model_name}")
    print("=" * 80)

    y_pred = cross_val_predict(
        best_model,
        X,
        y,
        cv=skf,
        method="predict",
        n_jobs=-1
    )

    # 大多数模型都有 predict_proba
    if hasattr(best_model, "predict_proba"):
        y_proba = cross_val_predict(
            best_model,
            X,
            y,
            cv=skf,
            method="predict_proba",
            n_jobs=-1
        )[:, 1]
    else:
        y_proba = None

    acc = accuracy_score(y, y_pred)
    pre = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    if y_proba is not None:
        auc = roc_auc_score(y, y_proba)
    else:
        auc = np.nan

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {pre:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    print(f"ROC-AUC  : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y,
        y_pred,
        target_names=["weak", "strong"]
    ))

    overall_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": pre,
        "Recall": rec,
        "F1": f1,
        "ROC_AUC": auc
    })


# =========================
# 8.1 整体预测结果汇总
# =========================
overall_results_df = pd.DataFrame(overall_results)

print("\n" + "=" * 80)
print("Overall CV Prediction Summary")
print("=" * 80)
print(overall_results_df)


# =========================
# 8.2 选择最优模型
# =========================
best_model_name = overall_results_df.sort_values(
    by="F1",
    ascending=False
).iloc[0]["Model"]

best_model = best_estimators[best_model_name]

print("\n" + "=" * 80)
print(f"Best model based on overall CV F1-score: {best_model_name}")
print("=" * 80)

print("\nBest model pipeline:")
print(best_model)

df_PDT_dft_best_overall = overall_results_df[
    overall_results_df["Model"] == best_model_name
].copy()

df_PDT_dft_best_summary = pd.DataFrame({
    "method": ["DFT"],
    "best_model": [best_model_name],
    "test_accuracy": [f"{df_PDT_dft_best_overall['Accuracy'].iloc[0]:.4f}"],
    "test_precision": [f"{df_PDT_dft_best_overall['Precision'].iloc[0]:.4f}"],
    "test_recall": [f"{df_PDT_dft_best_overall['Recall'].iloc[0]:.4f}"],
    "test_f1": [f"{df_PDT_dft_best_overall['F1'].iloc[0]:.4f}"],
    "test_roc_auc": [f"{df_PDT_dft_best_overall['ROC_AUC'].iloc[0]:.4f}"]
})

df_PDT_best_summary = pd.concat([df_PDT_dft_md_best_summary, df_PDT_dft_best_summary], ignore_index=True)

存在的特征列数: 15
缺失的列: []

最终用于建模的特征数: 15
最终特征列:
['es1_ev_high_pred', 'fs1_high_pred', 'et1_ev_high_pred', 'delta_est_ev_high_pred', 'min_abs_s1_tn_ev_high_pred', 'd_index_ang_high_pred', 't_index_ang_high_pred', 'zpe_ha_pred', 'gcorr_ha_pred', 'alpha_iso_bohr3_pred', 's_vib_cal_molk_pred', 'svib_frac_pred', 'hlg_kjmol_high_pred', 'dipole_gs_debye_high_pred', 'ci_index']

标签分布：
PDT_bin
1    130
0    113
Name: count, dtype: int64

===== 5-Fold Cross Validation Results =====
accuracy  : 0.7243 ± 0.0905
precision : 0.7518 ± 0.0933
recall    : 0.7308 ± 0.0988
f1        : 0.7387 ± 0.0854
roc_auc   : 0.8168 ± 0.0755

===== Overall CV Prediction Metrics =====
Accuracy : 0.7242798353909465
Precision: 0.7480314960629921
Recall   : 0.7307692307692307
F1-score : 0.7392996108949417
ROC-AUC  : 0.8103471749489447

===== Confusion Matrix =====
[[81 32]
 [35 95]]

===== Classification Report =====
              precision    recall  f1-score   support

        weak       0.70      0.72      0.71       113
      strong       0.75      0.73      0.74       130

    accuracy                           0.72       243
   macro avg       0.72      0.72      0.72       243
weighted avg       0.72      0.72      0.72       243


类别分布:
PDT_bin
1    130
0    113
Name: count, dtype: int64
XGBoost scale_pos_weight: 0.8692

================================================================================
Start Grid Search for: RandomForest
================================================================================

Best parameters for RandomForest:
{'model__max_depth': None, 'model__max_features': 0.5, 'model__min_samples_leaf': 1, 'model__n_estimators': 100}

Best mean CV f1: 0.7540
accuracy  : 0.7408 ± 0.0779
precision : 0.7613 ± 0.0710
recall    : 0.7538 ± 0.1182
f1        : 0.7540 ± 0.0784
roc_auc   : 0.8148 ± 0.0877

================================================================================
Start Grid Search for: XGBoost
================================================================================

Best parameters for XGBoost:
{'model__colsample_bytree': 0.8, 'model__learning_rate': 0.1, 'model__max_depth': 3, 'model__n_estimators': 100, 'model__subsample': 0.8}

Best mean CV f1: 0.7520
accuracy  : 0.7410 ± 0.1030
precision : 0.7626 ± 0.0895
recall    : 0.7462 ± 0.1289
f1        : 0.7520 ± 0.1033
roc_auc   : 0.7951 ± 0.0890

================================================================================
Start Grid Search for: MLP
================================================================================

Best parameters for MLP:
{'model__alpha': 0.0001, 'model__hidden_layer_sizes': (128,), 'model__learning_rate_init': 0.0005}

Best mean CV f1: 0.6522
accuracy  : 0.6742 ± 0.0870
precision : 0.7565 ± 0.0929
recall    : 0.5846 ± 0.1341
f1        : 0.6522 ± 0.1002
roc_auc   : 0.7459 ± 0.0992

================================================================================
Start Grid Search for: LogisticRegression
================================================================================

Best parameters for LogisticRegression:
{'model__C': 10, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

Best mean CV f1: 0.7272
accuracy  : 0.7283 ± 0.0719
precision : 0.7918 ± 0.0959
recall    : 0.6846 ± 0.1112
f1        : 0.7272 ± 0.0757
roc_auc   : 0.7958 ± 0.0839

================================================================================
Grid Search Summary
================================================================================
                Model  accuracy_mean  accuracy_std  precision_mean  \
0        RandomForest       0.740833      0.077932        0.761316
1             XGBoost       0.741000      0.102951        0.762621
2                 MLP       0.674167      0.086962        0.756470
3  LogisticRegression       0.728333      0.071883        0.791790

   precision_std  recall_mean  recall_std   f1_mean    f1_std  roc_auc_mean  \
0       0.070965     0.753846    0.118171  0.753971  0.078388      0.814802
1       0.089511     0.746154    0.128947  0.751967  0.103347      0.795105
2       0.092937     0.584615    0.134120  0.652196  0.100194      0.745862
3       0.095929     0.684615    0.111206  0.727173  0.075717      0.795804

   roc_auc_std                                        Best_Params
0     0.087703  {'model__max_depth': None, 'model__max_feature...
1     0.088956  {'model__colsample_bytree': 0.8, 'model__learn...
2     0.099186  {'model__alpha': 0.0001, 'model__hidden_layer_...
3     0.083908  {'model__C': 10, 'model__penalty': 'l1', 'mode...

================================================================================
Overall CV Prediction Metrics: RandomForest
================================================================================
Accuracy : 0.7407
Precision: 0.7597
Recall   : 0.7538
F1-score : 0.7568
ROC-AUC  : 0.8097

Confusion Matrix:
[[82 31]
 [32 98]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.72      0.73      0.72       113
      strong       0.76      0.75      0.76       130

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.74      0.74      0.74       243


================================================================================
Overall CV Prediction Metrics: XGBoost
================================================================================
Accuracy : 0.7407
Precision: 0.7638
Recall   : 0.7462
F1-score : 0.7549
ROC-AUC  : 0.7948

Confusion Matrix:
[[83 30]
 [33 97]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.72      0.73      0.72       113
      strong       0.76      0.75      0.75       130

    accuracy                           0.74       243
   macro avg       0.74      0.74      0.74       243
weighted avg       0.74      0.74      0.74       243


================================================================================
Overall CV Prediction Metrics: MLP
================================================================================
Accuracy : 0.6749
Precision: 0.7525
Recall   : 0.5846
F1-score : 0.6580
ROC-AUC  : 0.7308

Confusion Matrix:
[[88 25]
 [54 76]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.62      0.78      0.69       113
      strong       0.75      0.58      0.66       130

    accuracy                           0.67       243
   macro avg       0.69      0.68      0.67       243
weighted avg       0.69      0.67      0.67       243


================================================================================
Overall CV Prediction Metrics: LogisticRegression
================================================================================
Accuracy : 0.7284
Precision: 0.7807
Recall   : 0.6846
F1-score : 0.7295
ROC-AUC  : 0.7781

Confusion Matrix:
[[88 25]
 [41 89]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.68      0.78      0.73       113
      strong       0.78      0.68      0.73       130

    accuracy                           0.73       243
   macro avg       0.73      0.73      0.73       243
weighted avg       0.73      0.73      0.73       243


================================================================================
Overall CV Prediction Summary
================================================================================
                Model  Accuracy  Precision    Recall        F1   ROC_AUC
0        RandomForest  0.740741   0.759690  0.753846  0.756757  0.809666
1             XGBoost  0.740741   0.763780  0.746154  0.754864  0.794758
2                 MLP  0.674897   0.752475  0.584615  0.658009  0.730769
3  LogisticRegression  0.728395   0.780702  0.684615  0.729508  0.778080

================================================================================
Best model based on overall CV F1-score: RandomForest
================================================================================

Best model pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        max_features=0.5, n_jobs=-1,
                                        random_state=212))])

### 2.3 MD

In [ ]:
########################################### MD #####################################################

# =========================
# 1. 选择输入特征和标签
# =========================
feature_cols = MD_cols

target_col = 'PDT_bin'

# 只保留实际存在的列
existing_feature_cols = [col for col in feature_cols if col in data_PDT.columns]
missing_cols = [col for col in feature_cols if col not in data_PDT.columns]

print("存在的特征列数:", len(existing_feature_cols))
print("缺失的列:", missing_cols)

# 提取数据
X = data_PDT[existing_feature_cols].copy()
y = data_PDT[target_col].copy()

# 2. 自动去掉非数值列
# =========================
non_numeric_cols = X.select_dtypes(exclude=[np.number]).columns.tolist()
if len(non_numeric_cols) > 0:
    print("\n以下列不是数值列，将被移除：")
    print(non_numeric_cols)

X = X.select_dtypes(include=[np.number]).copy()

print("\n最终用于建模的特征数:", X.shape[1])
print("最终特征列:")
print(X.columns.tolist())

# =========================
# 3. 标签编码
# strong -> 1, weak -> 0
# =========================
y = y.map({'strong': 1, 'weak': 0})

# 检查是否有未映射成功的标签
if y.isnull().any():
    raise ValueError("PDT_bin 中存在不是 'strong' 或 'weak' 的标签，请检查数据。")

print("\n标签分布:")
print(y.value_counts())
# =========================
# 4. 定义五折分层交叉验证
# =========================
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=random_seed)

# =========================
# 5. 定义模型管道
# =========================
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('rf', RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=random_seed,
        n_jobs=-1,
        class_weight='balanced'
    ))
])

# =========================
# 6. 交叉验证评估
# =========================
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1',
    'roc_auc': 'roc_auc'
}

cv_results = cross_validate(
    pipeline,
    X,
    y,
    cv=skf,
    scoring=scoring,
    return_train_score=False,
    n_jobs=-1
)

print("\n===== 10-Fold Cross Validation Results =====")
for metric in scoring.keys():
    scores = cv_results[f'test_{metric}']
    print(f"{metric:10s}: {scores.mean():.4f} ± {scores.std():.4f}")

# =========================
# 7. 获取交叉验证整体预测结果
# =========================
y_pred = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict',
    n_jobs=-1
)

y_proba = cross_val_predict(
    pipeline,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# =========================
# 8. 输出整体指标
# =========================
print("\n===== Overall CV Prediction Metrics =====")
print("Accuracy :", accuracy_score(y, y_pred))
print("Precision:", precision_score(y, y_pred))
print("Recall   :", recall_score(y, y_pred))
print("F1-score :", f1_score(y, y_pred))
print("ROC-AUC  :", roc_auc_score(y, y_proba))

print("\n===== Confusion Matrix =====")
print(confusion_matrix(y, y_pred))

print("\n===== Classification Report =====")
print(classification_report(y, y_pred, target_names=['weak', 'strong']))


#################################### 调参 ########################################

# =========================
# 7. 模型调参 + 十折分层交叉验证
# =========================
# =========================
# 7.1 十折分层交叉验证设置
# =========================
skf = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=random_seed
)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
    "roc_auc": "roc_auc"
}

# 调参时以 F1-score 作为主指标
refit_metric = "f1"


# =========================
# 7.2 类别不平衡处理
# =========================
n_pos = np.sum(y == 1)
n_neg = np.sum(y == 0)

if n_pos == 0 or n_neg == 0:
    raise ValueError("y 中必须同时包含 strong 和 weak 两类。")

scale_pos_weight = n_neg / n_pos

print("\n类别分布:")
print(y.value_counts())
print(f"XGBoost scale_pos_weight: {scale_pos_weight:.4f}")


# =========================
# 7.3 定义模型和较小的参数搜索空间
# =========================
models_and_params = {
    "RandomForest": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", RandomForestClassifier(
                random_state=random_seed,
                n_jobs=-1,
                class_weight="balanced"
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [None, 5, 10],
            "model__min_samples_leaf": [1, 2],
            "model__max_features": ["sqrt", 0.5]
        }
    },

    "XGBoost": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("model", XGBClassifier(
                objective="binary:logistic",
                eval_metric="logloss",
                random_state=random_seed,
                n_jobs=-1,
                scale_pos_weight=scale_pos_weight
            ))
        ]),
        "param_grid": {
            "model__n_estimators": [100, 300],
            "model__max_depth": [2, 3],
            "model__learning_rate": [0.03, 0.1],
            "model__subsample": [0.8, 1.0],
            "model__colsample_bytree": [0.8, 1.0]
        }
    },

    "MLP": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", MLPClassifier(
                random_state=random_seed,
                max_iter=1000,
                early_stopping=True
            ))
        ]),
        "param_grid": {
            "model__hidden_layer_sizes": [(64,), (128,), (64, 32)],
            "model__alpha": [1e-4, 1e-3],
            "model__learning_rate_init": [1e-3, 5e-4]
        }
    },

    "LogisticRegression": {
        "pipeline": Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
            ("model", LogisticRegression(
                random_state=random_seed,
                class_weight="balanced",
                max_iter=2000
            ))
        ]),
        "param_grid": {
            "model__penalty": ["l1", "l2"],
            "model__C": [0.01, 0.1, 1, 10],
            "model__solver": ["liblinear"]
        }
    }
}


# =========================
# 7.4 对每个模型进行 GridSearchCV
# =========================
best_estimators = {}
summary_results = []

for model_name, item in models_and_params.items():

    print("\n" + "=" * 80)
    print(f"Start Grid Search for: {model_name}")
    print("=" * 80)

    grid_search = GridSearchCV(
        estimator=item["pipeline"],
        param_grid=item["param_grid"],
        scoring=scoring,
        refit=refit_metric,
        cv=skf,
        n_jobs=-1,
        return_train_score=False
    )

    grid_search.fit(X, y)

    best_estimators[model_name] = grid_search.best_estimator_

    print(f"\nBest parameters for {model_name}:")
    print(grid_search.best_params_)

    print(f"\nBest mean CV {refit_metric}: {grid_search.best_score_:.4f}")

    best_idx = grid_search.best_index_

    result_row = {
        "Model": model_name,
        "Best_Params": grid_search.best_params_
    }

    for metric in scoring.keys():
        mean_score = grid_search.cv_results_[f"mean_test_{metric}"][best_idx]
        std_score = grid_search.cv_results_[f"std_test_{metric}"][best_idx]

        result_row[f"{metric}_mean"] = mean_score
        result_row[f"{metric}_std"] = std_score

        print(f"{metric:10s}: {mean_score:.4f} ± {std_score:.4f}")

    summary_results.append(result_row)


# =========================
# 7.5 汇总不同模型的调参结果
# =========================
summary_df = pd.DataFrame(summary_results)

display_cols = [
    "Model",
    "accuracy_mean", "accuracy_std",
    "precision_mean", "precision_std",
    "recall_mean", "recall_std",
    "f1_mean", "f1_std",
    "roc_auc_mean", "roc_auc_std",
    "Best_Params"
]

summary_df = summary_df[display_cols]

print("\n" + "=" * 80)
print("Grid Search Summary")
print("=" * 80)
print(summary_df)


# =========================
# 8. 使用最佳模型进行整体交叉验证预测
# =========================
overall_results = []

for model_name, best_model in best_estimators.items():

    print("\n" + "=" * 80)
    print(f"Overall CV Prediction Metrics: {model_name}")
    print("=" * 80)

    y_pred = cross_val_predict(
        best_model,
        X,
        y,
        cv=skf,
        method="predict",
        n_jobs=-1
    )

    # 大多数模型都有 predict_proba
    if hasattr(best_model, "predict_proba"):
        y_proba = cross_val_predict(
            best_model,
            X,
            y,
            cv=skf,
            method="predict_proba",
            n_jobs=-1
        )[:, 1]
    else:
        y_proba = None

    acc = accuracy_score(y, y_pred)
    pre = precision_score(y, y_pred)
    rec = recall_score(y, y_pred)
    f1 = f1_score(y, y_pred)

    if y_proba is not None:
        auc = roc_auc_score(y, y_proba)
    else:
        auc = np.nan

    print(f"Accuracy : {acc:.4f}")
    print(f"Precision: {pre:.4f}")
    print(f"Recall   : {rec:.4f}")
    print(f"F1-score : {f1:.4f}")
    print(f"ROC-AUC  : {auc:.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y,
        y_pred,
        target_names=["weak", "strong"]
    ))

    overall_results.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": pre,
        "Recall": rec,
        "F1": f1,
        "ROC_AUC": auc
    })


# =========================
# 8.1 整体预测结果汇总
# =========================
overall_results_df = pd.DataFrame(overall_results)

print("\n" + "=" * 80)
print("Overall CV Prediction Summary")
print("=" * 80)
print(overall_results_df)


# =========================
# 8.2 选择最优模型
# =========================
best_model_name = overall_results_df.sort_values(
    by="F1",
    ascending=False
).iloc[0]["Model"]

best_model = best_estimators[best_model_name]

print("\n" + "=" * 80)
print(f"Best model based on overall CV F1-score: {best_model_name}")
print("=" * 80)

print("\nBest model pipeline:")
print(best_model)

df_PDT_md_best_overall = overall_results_df[
    overall_results_df["Model"] == best_model_name
].copy()

df_PDT_md_best_summary = pd.DataFrame({
    "method": ["MD"],
    "best_model": [best_model_name],
    "test_accuracy": [f"{df_PDT_md_best_overall['Accuracy'].iloc[0]:.4f}"],
    "test_precision": [f"{df_PDT_md_best_overall['Precision'].iloc[0]:.4f}"],
    "test_recall": [f"{df_PDT_md_best_overall['Recall'].iloc[0]:.4f}"],
    "test_f1": [f"{df_PDT_md_best_overall['F1'].iloc[0]:.4f}"],
    "test_roc_auc": [f"{df_PDT_md_best_overall['ROC_AUC'].iloc[0]:.4f}"]
})

df_PDT_best_summary = pd.concat([df_PDT_dft_md_best_summary, df_PDT_md_best_summary, df_PDT_dft_best_summary], ignore_index=True)

存在的特征列数: 6
缺失的列: []

最终用于建模的特征数: 6
最终特征列:
['vdw_energy_kjmol', 'total_energy_kjmol', 'rg_center_norm', 'rdf_first_peak_height', 'hbond_dynamic', 'hbond_static']

标签分布:
PDT_bin
1    130
0    113
Name: count, dtype: int64

===== 10-Fold Cross Validation Results =====
accuracy  : 0.6245 ± 0.0944
precision : 0.6624 ± 0.0814
recall    : 0.6154 ± 0.1418
f1        : 0.6318 ± 0.0988
roc_auc   : 0.6820 ± 0.1084

===== Overall CV Prediction Metrics =====
Accuracy : 0.6255144032921811
Precision: 0.6611570247933884
Recall   : 0.6153846153846154
F1-score : 0.6374501992031872
ROC-AUC  : 0.6780122532334921

===== Confusion Matrix =====
[[72 41]
 [50 80]]

===== Classification Report =====
              precision    recall  f1-score   support

        weak       0.59      0.64      0.61       113
      strong       0.66      0.62      0.64       130

    accuracy                           0.63       243
   macro avg       0.63      0.63      0.63       243
weighted avg       0.63      0.63      0.63       243


类别分布:
PDT_bin
1    130
0    113
Name: count, dtype: int64
XGBoost scale_pos_weight: 0.8692

================================================================================
Start Grid Search for: RandomForest
================================================================================

Best parameters for RandomForest:
{'model__max_depth': 10, 'model__max_features': 0.5, 'model__min_samples_leaf': 1, 'model__n_estimators': 100}

Best mean CV f1: 0.6446
accuracy  : 0.6278 ± 0.1345
precision : 0.6591 ± 0.1279
recall    : 0.6385 ± 0.1540
f1        : 0.6446 ± 0.1329
roc_auc   : 0.6867 ± 0.1104

================================================================================
Start Grid Search for: XGBoost
================================================================================

Best parameters for XGBoost:
{'model__colsample_bytree': 1.0, 'model__learning_rate': 0.03, 'model__max_depth': 2, 'model__n_estimators': 300, 'model__subsample': 1.0}

Best mean CV f1: 0.6620
accuracy  : 0.6528 ± 0.1067
precision : 0.7022 ± 0.1133
recall    : 0.6385 ± 0.1243
f1        : 0.6620 ± 0.0993
roc_auc   : 0.6875 ± 0.0909

================================================================================
Start Grid Search for: MLP
================================================================================

Best parameters for MLP:
{'model__alpha': 0.0001, 'model__hidden_layer_sizes': (64, 32), 'model__learning_rate_init': 0.0005}

Best mean CV f1: 0.6972
accuracy  : 0.5352 ± 0.0099
precision : 0.5352 ± 0.0099
recall    : 1.0000 ± 0.0000
f1        : 0.6972 ± 0.0085
roc_auc   : 0.4846 ± 0.0924

================================================================================
Start Grid Search for: LogisticRegression
================================================================================

Best parameters for LogisticRegression:
{'model__C': 1, 'model__penalty': 'l2', 'model__solver': 'liblinear'}

Best mean CV f1: 0.6651
accuracy  : 0.6460 ± 0.0895
precision : 0.6702 ± 0.0860
recall    : 0.6692 ± 0.1289
f1        : 0.6651 ± 0.0987
roc_auc   : 0.6904 ± 0.0913

================================================================================
Grid Search Summary
================================================================================
                Model  accuracy_mean  accuracy_std  precision_mean  \
0        RandomForest       0.627833      0.134549        0.659107
1             XGBoost       0.652833      0.106675        0.702164
2                 MLP       0.535167      0.009929        0.535167
3  LogisticRegression       0.646000      0.089509        0.670153

   precision_std  recall_mean  recall_std   f1_mean    f1_std  roc_auc_mean  \
0       0.127913     0.638462    0.154038  0.644640  0.132895      0.686742
1       0.113302     0.638462    0.124273  0.662027  0.099332      0.687471
2       0.009929     1.000000    0.000000  0.697155  0.008474      0.484615
3       0.086043     0.669231    0.128947  0.665146  0.098741      0.690385

   roc_auc_std                                        Best_Params
0     0.110434  {'model__max_depth': 10, 'model__max_features'...
1     0.090939  {'model__colsample_bytree': 1.0, 'model__learn...
2     0.092416  {'model__alpha': 0.0001, 'model__hidden_layer_...
3     0.091253  {'model__C': 1, 'model__penalty': 'l2', 'model...

================================================================================
Overall CV Prediction Metrics: RandomForest
================================================================================
Accuracy : 0.6296
Precision: 0.6587
Recall   : 0.6385
F1-score : 0.6484
ROC-AUC  : 0.6719

Confusion Matrix:
[[70 43]
 [47 83]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.60      0.62      0.61       113
      strong       0.66      0.64      0.65       130

    accuracy                           0.63       243
   macro avg       0.63      0.63      0.63       243
weighted avg       0.63      0.63      0.63       243


================================================================================
Overall CV Prediction Metrics: XGBoost
================================================================================
Accuracy : 0.6543
Precision: 0.6917
Recall   : 0.6385
F1-score : 0.6640
ROC-AUC  : 0.6860

Confusion Matrix:
[[76 37]
 [47 83]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.62      0.67      0.64       113
      strong       0.69      0.64      0.66       130

    accuracy                           0.65       243
   macro avg       0.65      0.66      0.65       243
weighted avg       0.66      0.65      0.65       243


================================================================================
Overall CV Prediction Metrics: MLP
================================================================================
Accuracy : 0.5350
Precision: 0.5350
Recall   : 1.0000
F1-score : 0.6971
ROC-AUC  : 0.4894

Confusion Matrix:
[[  0 113]
 [  0 130]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.00      0.00      0.00       113
      strong       0.53      1.00      0.70       130

    accuracy                           0.53       243
   macro avg       0.27      0.50      0.35       243
weighted avg       0.29      0.53      0.37       243


================================================================================
Overall CV Prediction Metrics: LogisticRegression
================================================================================
Accuracy : 0.6461
Precision: 0.6692
Recall   : 0.6692
F1-score : 0.6692
ROC-AUC  : 0.6901

Confusion Matrix:
[[70 43]
 [43 87]]

Classification Report:
              precision    recall  f1-score   support

        weak       0.62      0.62      0.62       113
      strong       0.67      0.67      0.67       130

    accuracy                           0.65       243
   macro avg       0.64      0.64      0.64       243
weighted avg       0.65      0.65      0.65       243


================================================================================
Overall CV Prediction Summary
================================================================================
                Model  Accuracy  Precision    Recall        F1   ROC_AUC
0        RandomForest  0.629630   0.658730  0.638462  0.648438  0.671886
1             XGBoost  0.654321   0.691667  0.638462  0.664000  0.686045
2                 MLP  0.534979   0.534979  1.000000  0.697051  0.489449
3  LogisticRegression  0.646091   0.669231  0.669231  0.669231  0.690129

================================================================================
Best model based on overall CV F1-score: MLP
================================================================================

Best model pipeline:
Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler()),
                ('model',
                 MLPClassifier(early_stopping=True, hidden_layer_sizes=(64, 32),
                               learning_rate_init=0.0005, max_iter=1000,
                               random_state=212))])

In [19]:
df_PDT_best_summary

,method,best_model,test_accuracy,test_precision,test_recall,test_f1,test_roc_auc
0,DFT_MD,RandomForest,0.7449,0.7656,0.7538,0.7597,0.8049
1,MD,MLP,0.5350,0.5350,1.0000,0.6971,0.4894
2,DFT,RandomForest,0.7407,0.7597,0.7538,0.7568,0.8097